contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #iridanext channel"
    url: https://nfcore.slack.com/channels/iridanext
    about: Discussion about the nf-core/iridanext pipeline
